name: Publish Docker Image

on:
  push:
    branches: [ 'main' ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - uses: docker/build-push-action@v5
      with:
        push: true
        tags: mfrancis95/chocolate-doom-build
